### ISSUE TITLE
Minor Fix to be Made in readme file of this repository

### ISSUE THREAD

**Issue by atharvashirdhankar** [appwrite/playground-for-kotlin#4]
Since the readme file in the root directory of this repository is for `playground for kotlin` .
But at some places in readme it is written as `dart`.
So required changes to be made at some places.

**Reference ScreenShot from readme file of Playground for Kotlin:**

![SS2](https://user-images.githubusercontent.com/72031540/138569300-1b4e51d8-6893-4e66-865b-53d76e960c5e.JPG)

Can I do the required changes

**Comment by chaterinamf** [comment]
Hello, may I do this? and what is the issue that you want me to solve?

**Comment by atharvashirdhankar** [comment]
I m working on this issue. Just waited for notification from maintainers.

**Comment by atharvashirdhankar** [comment]
PR for the following issue #5
